# Generated by Django 4.1.4 on 2023-05-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('passport', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=200)),
                ('date', models.DateTimeField(null=True)),
                ('location', models.CharField(default='SOME STRING', max_length=50)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
